from abc import ABC, abstractmethod
import torch
class BaseDecoder(ABC):
    @abstractmethod
    def generate(self, context_tokens, latent: torch.Tensor, **kw): ...
class CodeDecoder(BaseDecoder): ...
class MathDecoder(BaseDecoder): ...
class TextDecoder(BaseDecoder): ...
