from abc import ABC, abstractmethod
from typing import Any
import torch

class BaseEncoder(ABC):
    @abstractmethod
    def encode(self, x: Any) -> torch.Tensor: ...

class ContextEncoder(BaseEncoder): ...
class TargetEncoder(BaseEncoder): ...

class CodeContextEncoder(ContextEncoder): ...
class MathContextEncoder(ContextEncoder): ...
class TextContextEncoder(ContextEncoder): ...
class CodeTargetEncoder(TargetEncoder): ...
class MathTargetEncoder(TargetEncoder): ...
class TextTargetEncoder(TargetEncoder): ...
